### ISSUE TITLE
Request validation of string attributes set to null fails

### ISSUE THREAD

**Issue by psvo** [Captain-P-Goldfish/SCIM-SDK#103]
If a string attribute is set to `null`, the request fails with type mismatch error. But it seems the same issue affects other attribute types too.

For example:
```
POST /scim/v2/Groups
Content-Type: application/scim+json

{
  "displayName": "my group",
  "externalId": null,
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:Group"
  ]
}
```
Fails with:
```
{
  "detail": "value of field with name 'urn:ietf:params:scim:schemas:core:2.0:Group:externalId' is not of type 'string' but of type: null",
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:Error"
  ],
  "status": 400
}
```

According to RFC 7643 it seems like an incorrect behavior and the request should be treated the same way as when the `externalId` attribute is omitted:

> 2.5.  Unassigned and Null Values
> Unassigned attributes, the null value, or an empty array (in the case of a multi-valued attribute) SHALL be considered to be equivalent in "state".  Assigning an attribute with the value "null" or an empty array (in the case of multi-valued attributes) has the effect of making the attribute "unassigned".  When a resource is expressed in JSON format, unassigned attributes, although they are defined in schema, MAY be omitted for compactness.

I believe the safest/easiest fix would to replace `NullNode` with `null` at the beginning of `SchemaValidator#checkMetaAttributeOnDocument` method. I tried that and it fixes the issue.

Would you be interested in a pull-request?

**Comment by Captain-P-Goldfish** [comment]
right I never tested this json null values.
A pull request would be great but please provide also unit tests that verify that no regression will be added in the future.

**Comment by psvo** [comment]
Ok, I'll try to write something. Although it might take me some time.
