### ISSUE TITLE
Inconsistent handling of string attributes set to an empty or blank string

### ISSUE THREAD

**Issue by psvo** [Captain-P-Goldfish/SCIM-SDK#104]
I'm not completely sure how empty/blank strings should be treated in SCIM, but the SCIM-SDK API seems to treat them a bit inconsistently.

1. Empty/blank string is accepted as a valid value of required string attribute.
2. Empty/blank string can be obtained by `ScimObjectNode#getStringAttribute(java.lang.String)`.
3. Empty/blank string cannot be set by `ScimObjectNode#setAttribute(java.lang.String, java.lang.String)`, It will be normalized to a missing value.

Example request:
```
POST http://localhost:8180/ssc/api/scim/v2/Groups
Content-Type: application/scim+json

{
  "displayName": "",
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:Group"
  ]
}
```

It seems it would be better if empty/blank strings would be treated consistently in SCIM-SDK API. Or is there some rationale I'm missing for this behavior?

I haven't found any mentions about empty/blank strings in the SCIM RFCs, so probably the setAttribute should not attempt string normalization?

**Comment by Captain-P-Goldfish** [comment]
point 1 and 2 are actually on purpose.
I developed this API not for users and groups only. I use it also for defining configuration endpoints for custom resources in other programs. The intention behind 1 and 2 was that someone might want to handle empty strings as valid values which is why I accept them as valid. In order to change this you may use the attribute validation extension that is not defined by SCIM but is part of this API: https://github.com/Captain-P-Goldfish/SCIM-SDK/wiki/Attribute-validation

and last point 3. This is indeed somehow inconsistent but changing this would be a breaking change. A better solution would probably be adding a new method "setBlankAttribute(String name, String value)" and here the value should be left untouched. What do you think?

**Comment by psvo** [comment]
I totally agree 1 and 2 is correct behavior and it aligns with the SCIM RFC.

Ad 3:

The `setBlankAttribute(String name, String value)` you suggests should help for custom resources, but it does not change the issue with the pre-defined resources.

Are you considering to switch the predefined resources to this new method to avoid unintended attribute changes in case of POST(with blank string attributes)-GET(blank attributes are missing)-PUT(original blank attributes are removed)?

Alternatively, a configuration option could be added to switch the standard resources to use the setBlankAttribute.

Also, would it be possible to use the non-standard validation extension for the `User:userName`, because according to the RFC: "Each User MUST include a non-empty userName value". Now an empty string in the userName is accepted and it has to be handled explicitly by user. Or is that against your policy?

**Comment by Captain-P-Goldfish** [comment]
I don't think that I want to have this method set as default for the existing resources. This is more about usability. I agree that I should change the check from "isBlank" to "isNull" and at least add empty strings when set. But I wouldn't want to have my resources pumped up with null values. Normally I write an JPA entity that represents a resource (e.g. User) in the database and that is then parsed into the SCIM representation. If several values are null and the API would also add null-values by default the whole resource would full of unwanted fields in the JSON structure.

Would you agree that changing the check from "isBlank" to "isNull" is enough?

**Comment by psvo** [comment]
> I agree that I should change the check from "isBlank" to "isNull" and at least add empty strings when set. **But I wouldn't want to have my resources pumped up with null values.**

I believe this is a misunderstanding. I haven't intended to ask for anything like that.

Anyway, if I got your changes correctly, the empty/blank strings are now passing through in both directions untouched.

Originally I understood you don't want to do such a change to the generic API due to compatibility concerns, so I was trying to suggest some alternative - obviously I failed. ;-)

But I love the new behavior and IMO it solves all the problems with blank/empty nicely. Thanks!

**Comment by Captain-P-Goldfish** [comment]
This might be not backwards compatible in any case but I agreed with you that this was inconsistent behaviour and so I decided to change it and I will simply list it in the release notes for 1.9.0.
So I guess this ticket can be closed. Reopen if I missed anything
