### ISSUE TITLE
Patch operation on multivalue attributes may fail to remove the correct values

### ISSUE THREAD

**Issue by psvo** [Captain-P-Goldfish/SCIM-SDK#111]
When path in patch-remove operation is matching multiple values in multivalue attribute, it only removes correctly the first one. 

The issue is in `PatchTargetHandler#handleDirectMultiValuedComplexPathReference`:

```java
     for ( int i = 0 ; i < matchingComplexNodes.size() ; i++ )
      {
        multiValued.remove(matchingComplexNodes.get(i).getIndex());
        changeWasMade = true;
      }
```

After the first matching node is removed, the indexes in the multiValued shifts. Thus the next removal removes an incorrect node.

It seems the easiest fix would be to just iterate the matchingComplexNodes in a reverse order. I assume that the values returned by getIndex() are always increasing with position in the matchingComplexNodes list.

It's easy to reproduce on Group resource with multiple members and a patch operation like:

```json
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "remove",
      "path": "members[value eq \"member1\" or value eq \"member2\"]"
    }
  ]
}
```

Unfortunately, I won't be able to provide a patch with testcases in reasonable time.

**Comment by Captain-P-Goldfish** [comment]
thx for reporting this. I fixed it.
