### ISSUE TITLE
addtionalProperties is missing

### ISSUE THREAD

**Issue by skathery1985** [Captain-P-Goldfish/SCIM-SDK#113]
I tried the following json schema and used "addtionalProperties" keyword to control the handling of extra stuff, but it seems no support for it

Couldn't find it in SchemaValidator.java

```
.
.
.
,
  "additionalProperties": false,
  "meta": {
    "resourceType": "Schema",
    "created": "2019-10-18T14:51:11+02:00",
    "lastModified": "2019-10-18T14:51:11+02:00",
    "location": "/Schemas/User"
  }
}
```

**Comment by Captain-P-Goldfish** [comment]
A field with name "additionalProperties" is not part of the predefined user schema. If you need this field for a custom usecase you may copy the user-schema add the property field and simply register your UserHandler implementation with that schema.

Registering a custom user schema is pretty easy by defining a new Endpoint. See: https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/master/scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/endpoints/base/UserEndpointDefinition.java

If this does not help you please provide some more information

**Comment by skathery1985** [comment]
Thank you for reply, I already added custom endpoint it explained very nice thanks for that

But I'm talking about JSON schema properties
please take a look at **5.4.4.  additionalProperties, properties and patternProperties** in json schema validation draft

https://tools.ietf.org/html/draft-fge-json-schema-validation-00#page-12

I see additionalProperties is very important in scim

**Comment by Captain-P-Goldfish** [comment]
Could you explain why these properties are important? I cannot see any relevant relation to SCIM here. Also the validation of SCIM resources is not bound to any other RFC than 7643.
By the way the draft is pretty much outdated (February 2013). I do not think that it will ever reach its final state. But there is a newer draft trying to define a proper schemata for JSON documents. You can find it here: https://json-schema.org/specification.html

**Comment by Captain-P-Goldfish** [comment]
I am going to close. Feel free to reopen if you have anything else important on your mind regarding this issue.
