### ISSUE TITLE
Query and path on extension property seems to not work

### ISSUE THREAD

**Issue by psvo** [Captain-P-Goldfish/SCIM-SDK#114]
I'm trying to filter by manager property from the enterprise user extension. But I don't get any results. Also, if I try to remove the manager property with a PATCH request, it doesn't work for me either.

The filter query:
```
/Users/?filter=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:manager.value eq "managerid"
```

The PATCH request:
```
PATCH /Users/userid
Content-Type: application/scim+json

{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp",
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
  ],
  "Operations": [
    {
      "op": "remove",
      "path": "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:manager"
    }
  ]
}
```

Although I believe the queries are ok, I'm not totally sure it's not error on my side.

**Comment by Captain-P-Goldfish** [comment]
This is definitely my fault.
I forgot to delegate the filter expressions to the extension within the document.
And the patch problem is not restricted to extensions. This is a basic implementation error that misses to remove complex types if the fully qualified attribute path is used on either extensions or the main resource.
I am already at it.
