### ISSUE TITLE
Lots of allocations inside JsonHelper 

### ISSUE THREAD

**Issue by hamiltont** [Captain-P-Goldfish/SCIM-SDK#129]
Just reporting in case it slipped notice, feel free to close if the current approach is intentional

Inside JsonHelper, almost every method creates a new ObjectMapper. As JsonHelper is used for every API call, this seems to be a fair number of allocations. OM is not just a simple DTO object it has a few internal classes with non-trivial internal structures. 

I have not tested this at all, but suspect you could see better performance (both req/sec and memory thrashing) by using a pool of OMs. Ideally, callers would be able to configure the pool size to match the server worker thread pool size. 

Having a OM pool would prevent the repeated allocations. While (IIUC) OM is a thread-safe API (so you could just use a single OM), having a pool also prevents slowdowns from thread synchronization

**Comment by Captain-P-Goldfish** [comment]
I created some performance tests to check the execution performance on server side if I modify the `createUser` method in the `UserHandler` in the `spring-boot-example` as follows:

```
@Override
  public User createResource(User resource, Authorization authorization)
  {
    final String userId = UUID.randomUUID().toString();
    if (inMemoryMap.containsKey(userId))
    {
      throw new ConflictException("resource with id '" + userId + "' does already exist");
    }
    resource.setId(userId);
    inMemoryMap.put(userId, resource);
    resource.getMeta().ifPresent(meta -> {
      meta.setCreated(Instant.now());
      meta.setLastModified(Instant.now());
    });
    return JsonHelper.readJsonDocument(resource.toString(), User.class);
  }
```

I then started the sample and increased the `maxOperations` value for bulk to 50. Afterwards I tested both variations. Always using `new ObjectMapper` and a second test with a static instance of `ObjectMapper`.
I then wrote a sample-client that created 24.499 users and deleted them again. Both variations needed exactly 11 seconds for completion. Of course I tested both variations several times.
So I was not able to gain any relevant performance.

Client
```
      Instant startTime = Instant.now();
      createUsers(scimRequestBuilder, serviceProviderConfig);
      deleteAllUsers(scimRequestBuilder);
      Instant endTime = Instant.now();
      Duration diff = Duration.between(startTime, endTime);
      log.warn("{}", DurationFormatUtils.formatDuration(diff.toMillis(), "**H:mm:ss**", true));
      log.info("******************************************************************");
```

Logoutput
```
16 Mär 2021 22:21:29,716 [main] WARN  de.captaingoldfish.scim.sdk.springboot.sample.TestClient (TestClient.java:70) - **0:00:11**
```

So I do not think I can gain any relevant performance when pooling the `ObjectMapper`

I am going to close this issue. Feel free to reopen if you think that I am wrong.

**Comment by hamiltont** [comment]
> Feel free to reopen if you think that I am wrong.

I don't - an actual test like what you performed is more accurate than an educated guess. Appreciate you taking the time to test out the idea properly

**Comment by Captain-P-Goldfish** [comment]
I need to repeat the test...
I tested with a static instance so my test did not make any sense with a thread-safe api...
I am going to try it again later in the evening.

**Comment by Captain-P-Goldfish** [comment]
tried once more and this time with a pool based on the threads. No performance win that would be noticeable
