### ISSUE TITLE
Unable to use Basic Authorization with Keycloak

### ISSUE THREAD

**Issue by meden** [Captain-P-Goldfish/SCIM-SDK#134]
Hello, this is likely more a question than a bug, I'm using the issue tracking not having found other means.

I'm trying to use SCIM-SDK client against Keycloak by configuring it with `BasicAuth`:
```java
private ScimRequestBuilder createScimRequestBuilder(Config config)
    {
        ScimClientConfig scimClientConfig = ScimClientConfig.builder()
                .basicAuth(BasicAuth.builder()
                        .username(config.clientId)
                        .password(config.clientSecret)
                        .build()
                )
                .build();

        return new ScimRequestBuilder(config.scimBaseUrl, scimClientConfig);
    }
```

In Keycloak the client is configured as
![image](https://user-images.githubusercontent.com/824351/112288018-39a00d80-8c8d-11eb-8b84-9afa6dac1f77.png)

The SCIM extension has no explicitly authorized client, so it should allow them all.

How can I use client credentials just like I do with `org.keycloak.admin.client.Keycloak`, or `org.keycloak.authorization.client.AuthzClient`?

**Comment by Captain-P-Goldfish** [comment]
This is not possible.
You enabled the ClientCredentialsGrant for your client which enables you to claim an AccessToken at the OpenID Connect token endpoint. You'll be be to access the SCIM endpoints with such an AccessToken.

**Comment by meden** [comment]
OK, I suspected that. Do you have any alternative to suggest? I'm a bit reluctant to setup TLS authentication because I need backend communication on a trusted network.

In case I came up with a solution (i.e. adding bearer token support, with automatic refresh) would you be open to review a PR? No promises, though, as I have very little time these days, and it's something I have to agree with my company :slightly_smiling_face:.

**Comment by Captain-P-Goldfish** [comment]
a fast way to get the access token would be like this:

```
 @SneakyThrows
  private static String getAccessToken()
  {
    final String tokenEndpoint = "http://localhost:8080/auth/realms/master/protocol/openid-connect/token";
    ScimClientConfig scimClientConfig = ScimClientConfig.builder().socketTimeout(120).requestTimeout(120).build();
    try (ScimHttpClient scimHttpClient = new ScimHttpClient(scimClientConfig))
    {

      HttpPost httpPost = new HttpPost(tokenEndpoint);
      httpPost.addHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_FORM_URLENCODED);
      URIBuilder uriBuilder = new URIBuilder("http://localhost").addParameter("grant_type", "client_credentials")
                                                                .addParameter("client_id", "scim")
                                                                .addParameter("client_secret",
                                                                              "ffc6e64a-36d2-4ea7-9140-538c4a487459");
      httpPost.setEntity(new StringEntity(uriBuilder.build().getQuery()));
      HttpResponse httpResponse = scimHttpClient.sendRequest(httpPost);
      if (httpResponse.getHttpStatusCode() != 200)
      {
        throw new IllegalStateException("retrieving access token failed");
      }
      ObjectNode objectNode = (ObjectNode)JsonHelper.readJsonDocument(httpResponse.getResponseBody());
      return objectNode.get("access_token").asText();
    }
  }
```

Please not I did not put any specific effort into this. Since AccessTokens are short lived tokens you need to manually increase the lifetime in the WebAdmin or also need to handle refresh tokens.

**Comment by meden** [comment]
I'm actually already using the official clients too for users management, while I wanted to use your client for users provisioning, so I have already an easy way to get the token (and indeed I already tried to inject it in the SCIM request as header). But as you say I'm concerned about the token renewal. I'll see if I find something.

BTW, your code could be useful for an eventual `OidcAuth` in the `ScimClient`, so to not add any other dependency. For auto-renewal, something like `org.keycloak.admin.client.token.TokenManager` would be needed.

Thank you very much! :slightly_smiling_face:

**Comment by Captain-P-Goldfish** [comment]
Would be a possibility but I did not implement it on purpose because I did not want the weight of such an open specification on my shoulders.
