### ISSUE TITLE
Group patch remove operation is not working

### ISSUE THREAD

**Issue by infa-vnautiya** [Captain-P-Goldfish/SCIM-SDK#149]
I am trying to perform patch operation on a group and request is standard request as given in https://docs.microsoft.com/en-us/azure/active-directory/app-provisioning/use-scim-to-provision-users-and-groups#update-group-remove-members 
The payload is something like.

`{
    "schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
    "Operations": [{
        "op": "Remove",
        "path": "members",
        "value": [{
            "$ref": null,
            "value": "f648f8d5ea4e4cd38e9c"
        }]
    }]
}`
But the response is always some validation error
_values must not be set for remove operation but was: {\"$ref\":null,\"value\":\"f648f8d5ea4e4cd38e9c\"}"_
Please guide me here.

**Comment by Captain-P-Goldfish** [comment]
the request is illegal.
remove operations do not support the "value" attribute. you must set a path to explicitly determine the attribute to delete e.g.: 

`"path": "memebrs[value eq "f648f8d5ea4e4cd38e9c"]"`

this should achieve what you are trying to do

**Comment by koellth** [comment]
We got the same problem using Microsoft Azure as user directory. This seems to be standard Azure behavior. I doubt Microsoft is going to fix this in the near future :(

**Comment by Captain-P-Goldfish** [comment]
I am also not quite sure about a good solution here. Best would be if Atlassian would fix this behaviour. Trying to resolve whats in the request would be actually a complete new feature within the SCIM-SDK that is also not described by RFC7644

**Comment by koellth** [comment]
Hi @Captain-P-Goldfish , thanks for the quick answer. As I said, SCIM seems to be some kind of stepchild for Microsoft (or its Azure team). However, Azure probably is one of the most used IdP nowadays...

We need the Azure SCIM connection and have already invested some time in an implementation based on SCIM-SDK (and I really like the API). So I'm currently seriously thinking about a regex solution, but of course would prefer a more generic approach. Would you consider accepting a pull request for a "real" (but not RFC compliant) solution? Probably the starting point would be `PatchTargetHandler`?

**Comment by infa-vnautiya** [comment]
I raised this issue with Azure also but did not get satisfactory solution. They claimed that they are following this https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/scim/scim-groups where it can be seen that they are sending correct payload to remove member from group.

If its urgent, may I propose a hack here meanwhile in ResourceEndpointHandler ? (until they realized this issue).
```
 if(PatchOp.REMOVE.equals(operation.getOp()) && "members".equalsIgnoreCase(operation.getPath().get()) && operation.getValues() != null)
          {
            JsonNode node = JsonHelper.readJsonDocument(operation.getValues().get(0));
            operation.setValues(null);
            operation.setPath("members[value eq \""+ node.get("value").textValue() +"\"]");
          }
```

**Comment by koellth** [comment]
Hi @infa-vnautiya thanks, this is much appreciated. I was thinking about such a solution when writing about a "regex" approach :)

**Comment by fern-we** [comment]
Even their docs show they should be using the proper filter/eq syntax. So maybe you can work with them to file a ticket. https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/scim/scim-groups#remove-from-group

But having scim-sdk somehow support this non-standard behavior (behind a config flag) would be really useful!
