### ISSUE TITLE
does the server support tenants

### ISSUE THREAD

**Issue by Micjoyce** [Captain-P-Goldfish/SCIM-SDK#157]
I want to implement a scim server, Endpoint for example ` /Tenants/{tenantId}/**`, how to support multi-tenancy?
I see that `ResouceHandler` does not have a way to pass the TenantId parameter when processing

`
public abstract T updateResource(T resourceToUpdate, Authorization authorization);
`

https://datatracker.ietf.org/doc/html/rfc7644#section-6.1

**Comment by Captain-P-Goldfish** [comment]
Hi this is something that highly depends on your usecase.
I am working on two projects handling this usecase differently.

1. the [scim-for-keycloak](https://github.com/Captain-P-Goldfish/scim-for-keycloak) project supports this if you would treat the different realms as tenant. So one realm would be equal to one tenant. The implementation uses one `ResourceEndpoint` object per realm. So each realm has also its own `ServiceProvider` configuration.
2. At work we implemented a usecase that is actually quite similiar to the scim-for-keycloak usecase but with the difference that we do not use mulitple `ResourceEndpoint` instances but only a one instance. We have two different usecases here
   1. Users who can only make changes in the behalf of their tenant
   2. SuperUsers who can make changes to all tenants

The question in point 2 would be how you get the information of the tenant that should be worked on. In case 2.1 you should determine this by the authentication details and place the information in the `Authorization` object. So in the `ResourceHandler` you can directly determine the tenant on which the user is authorized.

But the funny usecase is 2.2 if a user has the rights to make changes on several tenants. We solved this simply by forcing the client to send the tenants id in a http-header. If the value in the header does not match one of its authorized values (maybe in case that the User has only access to a few but not all tenants) the response will be 403 forbidden.

Another way I can think of is adding a specific field to the schema e.g.:
```json
{
          "name": "tenant",
          "type": "string",
          "description": "The id of the tenant",
          "mutability": "writeOnly",
          "returned": "never",
          "uniqueness": "none",
          "multiValued": false,
          "required": true,
          "caseExact": false
        }
```

this would also be a way to force the client to directly mention the tenant on which the changes should be done.

So far that is everything I can think of. If you got some awesome ideas to make this better let me know.
