### ISSUE TITLE
Any chance of a new release soon? 

### ISSUE THREAD

**Issue by hamiltont** [Captain-P-Goldfish/SCIM-SDK#163]
I'm running into #131 which I see was fixed a while back. Any chance of a new release?  

PS - thanks for the nice library! I quite appreciate the auto-filtering, it got me started really quickly, but I'm ready to turn it off and try out direct sql for better performance

**Comment by Captain-P-Goldfish** [comment]
Hi I actually planned the release for this month but I got problems finding enough time to test the current api version. The new release completely reworked the schema validation implementation. 

I will try to release soon. I do not think that it should be more than 2 weeks.

**Comment by hamiltont** [comment]
👍  thanks

**Comment by Captain-P-Goldfish** [comment]
just triggered the release at sonatype. Should be available in the next hour

**Comment by hamiltont** [comment]
Pulled and testing, thanks!
