### ISSUE TITLE
Need to Publish Releases

### ISSUE THREAD

**Issue by fern-we** [Captain-P-Goldfish/SCIM-SDK#166]
Hi! I would love to use this project, but noticed that the latest versions are missing from Oss Sonatype, and Maven Central.

- https://oss.sonatype.org/#nexus-search;quick~io.github.captain-p-goldfish
- https://search.maven.org/search?q=io.github.captain-p-goldfish

**Comment by Captain-P-Goldfish** [comment]
Hi the groupId is outdated. The project started once with this groupId. Current version is:

```xml
<dependency>
    <groupId>de.captaingoldfish</groupId>
    <artifactId>scim-sdk-server</artifactId>
    <version>1.10.0</version>
</dependency>
```

Best regards
Pascal

**Comment by fern-we** [comment]
Thank you!! I'm so sorry to get confused. Could you we add the groupId/artifactIds in the wiki/Home to avoid confusion.

**Comment by Captain-P-Goldfish** [comment]
done :+1:
