### ISSUE TITLE
Error when removing group members via MS Azure

### ISSUE THREAD

**Issue by koellth** [Captain-P-Goldfish/SCIM-SDK#167]
Hi all,

we're trying to implement a SCIM solution for our application with MS Azure as a user directory and are currently using SCIM SDK 1.9.2 (also tried 1.10.0). So far I'm really enthusiastic about the SCIM SDK (though OTOH the MS SCIM implementation often seems quite strange).

However, when I remove a user from a group on the Azure side the following SCIM message is sent:
```
PATCH /scim/Groups/2752513
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "Remove",
            "path": "members",
            "value": [
                {
                    "value": "2392066"
                }
            ]
        }
    ]
}
```
(2752513 is my group id, 2392066 the id of the removed user). SCIM-SDK answers with

```
400 Bad Request
{
    "detail": "values must not be set for remove operation but was: {\"value\":\"2392066\"}",
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": 400,
    "scimType": "invalidValue"
}
```

Is this to be considered a bug on the Azure side? If yes, how is SCIM supposed to remove a group member (without sending the whole group)? Or am I missing something (or is there some kind of workaround)?

If this is an issue in SCIM SDK, of course I'm willing to help resolving this. So if you need some more data, just let me know. 

Cheers

Thomas

**Comment by koellth** [comment]
Sorry, I just saw this is a duplicate of #149. However, we probably can't influence behavior on Azure side, so it's hard to say what a valid solution for this would be.

**Comment by Captain-P-Goldfish** [comment]
I may provide a halfhearted workaround that parses such requests into valid requests. but I would only provide it for the specific request type shown above if this is enough that is? would help if you could provide information about other illegal requests of this kind

**Comment by koellth** [comment]
This would be much appreciated. AFAIK this is the only use case on Azure where SCIM-SDK throws an error. As the Azure implementation isn't very feature rich, I'm pretty confident I tested most/all relevant use cases. Of course I'll test again and give feedback.

**Comment by fern-we** [comment]
Even their docs show they should be using the proper filter/eq syntax. So maybe you can work with them to file a ticket. https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/scim/scim-groups#remove-from-group

But having scim-sdk somehow support this non-standard behavior (behind a config flag) would be really useful!

**Comment by Captain-P-Goldfish** [comment]
Alright I provided a fix that handles the pictured problem above. Feel free to try it and let me know if it works as expected

**Comment by koellth** [comment]
Thanks for your *really* quick solution. Yes, it now works without sending an error message and my other test cases still are OK.
However, `updateResource()` in our GroupHandler doesn't seem to be triggered for the remove case. Instead, `getResource()` is called (the add case works exactly as I expected). To be honest, I'm not sure what is supposed to happen.  Probably we have to implement this on a more low-level API?

**Comment by Captain-P-Goldfish** [comment]
The semantics for patch are described here:
https://github.com/Captain-P-Goldfish/SCIM-SDK/wiki/Patching-resources
See the *NOTE*-block at the top.

Since this is resolved I am closing this ticket.

**Comment by hrstn** [comment]
Is there a Backport for this issue ? i seem to run into the same error using the "scim-for-keycloak-kc-12-b2" with the 1.9.2 SDK

**Comment by Captain-P-Goldfish** [comment]
best thing to do would be to update keycloak. Several CVC's have been fixed since KC12 so the recommendation would be to do an update.
There are also some other important bug fixes in the scim-api that were resolved until KC15: https://github.com/Captain-P-Goldfish/scim-for-keycloak/releases
