### ISSUE TITLE
Using "active" flag on Azure

### ISSUE THREAD

**Issue by koellth** [Captain-P-Goldfish/SCIM-SDK#181]
The Microsoft Azure SCIM implementation sends patch requests for users in the following form:
```
{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
"Operations":[{"op":"Add","path":"name.formatted","value":"My display name"}]}
```
Please note the "active" flag is not sent. This is translated to a call to `updateResource()`. When I'm asking for
```
if (user.isActive().isPresent() && !user.isActive().get()) {
    deactivateUser(...);
}
```
the call is executed (probably because in the User constructor `active` is not `Optional` and so has to have some value).

When (soft-)deleting a user on the Azure side, a similar call is sent with active=false. My application needs this information to deactivate users on the app side.

Naively, I'd expect `user.isActive().isPresent()` to return false for the first call. Am I getting this wrong? Or is there a better way to distinguish these cases?

Regards

Thomas

**Comment by Captain-P-Goldfish** [comment]
Hi,
your if-expression is wrong. The deactivateUser method will be called for any deactivated user:

you check for `user.isActive().isPresent()` whch is `true` for as long as the `active-value` is `not null`. So regardless if active is `true` or `false` you will get `true`.

now you check for `!user.isActive().get()` this is true for any user that has an `active-value` of `false` so for any deactivated user.

The if expression should look like this:
```
if (user.isActive().orElse(false)) {
    deactivateUser(...);
}
```

This will assure that the expression returns `false` if the `active-value` is `false` or `null` and will return `true` only if the `active-value` is `true`

Does this fix your problem or did I misunderstand your question?

**Comment by koellth** [comment]
Of course you're right, the "patch" code loads my user before calling `updateResource()` and the user in question has already been deactivated. So I have to compare the old and new values and only call deactivate() when oldValue = true and newValue = false.

=> everything is working as expected
