### ISSUE TITLE
NPE when filtering by meta attribute

### ISSUE THREAD

**Issue by hynek5** [Captain-P-Goldfish/SCIM-SDK#186]
scim-sdk-server-1.9.2
scim-sdk-common-1.9.2

I'm trying to filter Users by meta.created attr in request query and NPE is thrown in FilterResourceResolver.retrieveComplexAttributeNode(JsonNode jsonNode, AttributeExpressionLeaf attributeExpressionLeaf), 

In my case jsonNode is  user: 
`{"schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],"id":"usr-0000000000000002","externalId":"425ffs","meta":{"created":"2021-07-15T17:07:55.955Z","lastModified":"2021-07-16T15:07:56.433Z"},"userName":"frontman","name":{"familyName":"Driveshaft","givenName":"Charlie"},"active":false,"emails":[{"type":"work","value":"frMan@mail.com"}]}`

and attributeExpressionLeaf:
`meta.created EQ "2021-07-15T17:07:55.955Z"`

In other cases `attributeExpressionLeaf.isMainSchemaNode()` returns true and it works fine. In this case the leaf is not considered to be main schema node and in else branch  extensionNode is set to null. Which makes sense since
`jsonNode.get("urn:ietf:params:scim:schemas:core:2.0:Meta")`
(in my case attributeExpressionLeaf.getSchemaAttribute().getSchema().getId().get() ~ urn:ietf:params:scim:schemas:core:2.0:Meta)

**Comment by Captain-P-Goldfish** [comment]
already fixed since 1.11.0
