### ISSUE TITLE
PATCH request returns in-memory resource instead of result from ResourceHandler

### ISSUE THREAD

**Issue by alexjp7** [Captain-P-Goldfish/SCIM-SDK#188]
Hi,

# Overview

When performing a PATCH request to add or replace an attribute for a resource, I've noticed that some attributes are mirrored from the PATCH request payload into the response payload, even when the mirrored properties aren't actually being used in the SCIM 2.0 server application.

# Example
**For example**,
 The SCIM server application uses the `role` property for a user. As apart of the implementation, the application code (sitting within the `ResourceHandler` implementation), only utilities the `roles.display` sub-attribute, and sets only the `roles.display` into response object. 

Given a request that includes **valid** SCIM 2.0 attributes, but are attributes that are not explicitly set into the response, are appearing in the JSON response payload. 

Request  - A PATCH request to add a role, that includes the `display`, `value`,  `type` and `primary`. 
```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "add",
            "path": "roles",
            "value": [
                {
                    "primary": false,
                    "type": "WindowsAzureActiveDirectoryRole",
                    "display": "Role 2",
                    "value": "Something Irrelevant"
                },
            ]
        }
    ]
}
```

The returned User object, from the `ResourceHandler` does NOT set anything except the `roles.display`.

Response 
```json
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    "id": "100325",
    "userName": "scim.test13",
    "displayName": "Dave",
    "active": true,
    "emails": [
        {
            "value": "dave@gmail.com",
            "type": "work",
            "primary": true
        }
    ],
    "phoneNumbers": [
        {
            "value": "551 1234",
            "type": "work"
        }
    ],
    "roles": [
        {
            "value": "Something Irrelevant",
            "display": "Role 1",
            "type": "WindowsAzureActiveDirectoryRole",
            "primary": false
        },
        {
            "value": "Something Irrelevant",
            "display": "Role 2",
            "type": "WindowsAzureActiveDirectoryRole",
            "primary": false
        }
    ],
    "meta": {
        "resourceType": "User",
        "created": "2021-04-23T02:15:38.378Z",
        "lastModified": "2021-07-21T17:45:13.223+10:00",
        "location": "https://********************/Users/100325",
        "version": "W/\"41BA1691F91FB9C9776DD2C18349540C051E59AD9E2339642B2CB0D32C7367D4FC7ABE6E9913B225A84B48E68AC2567BD2CF400149C6C9A93F5C84B1F5E98686\""
    },
}
```
Additional values are present in the response.

# Code Investigation

1. When looking at the current `ResourceEndpointHandler.patchResource()`  method,  I can see that  the follow line 
Line 1010
``` java 
ResourceNode patchedResourceNode = patchHandler.patchResource(resourceNode, patchOpRequest);
``` 
Is responsible for performing an in-memory update based on if the incoming node is different from the current state of the resource. The input reference of the `resourceNode`  (that is originally retrieved from server application) has its structure/values modified based on the incoming PATCH request. 

2. The `patchedResourceNode ` then becomes the result of the server applications update operation on the resource. The value that the `patchedResourceNode` has after this line is the desired response object.

Line 1032
```java
 patchedResourceNode = resourceHandler.updateResource(patchedResourceNode, authorization);
```

3. However, I noticed that return value for the `ResourceEndpointHandler.patchResource()` is the `resourceNode` after the in-memory update, as apposed to the intended `patchedResourceNode`.

Line 1049
```java
      JsonNode responseResource = responseValidator.validateDocument(resourceNode);
      return new UpdateResponse(responseResource, location, meta);
```

I am wondering if I am interpreting this behavior incorrectly, or is this in-fact unintentional? The main issue I'd like to solve is to ensure that all attributes that are in the response are attributed to a resource found in the server application.

Currently with this behavior,  attributes are appearing in the  response body that are not being set by the server application.

Is it possible to look into this issue, or otherwise suggest a work-around?
Thanks in advance

**Comment by Captain-P-Goldfish** [comment]
First of all, the code lines you are describing do not match the current version 1.11.0 so which version are you currently using?
And to the question: I don't think I get it yet...

Maybe you could provide me with your input, the output you expect and the output you actually get. This might help me understanding the underlying problem

But the behaviour of patch-operations is currently defined as follows:

1. validate patch-request
2. get current resource by calling `getResource`-method of the `ResourceHandler` implementation
3. modify the current resource in accordance with the given patch-operations
4. pass the modified object as if it was a `PUT` request to the `updateResource` method
5. take the response from the `updateResource`-method and validate it

Thats basically it. So I would be confused if the patch-behaviour would have anything to do with attributes present in the response that have not been set by yourself. But as I said I think I did not get it quite right.

**Comment by alexjp7** [comment]
My appoligies, the line numbers I referenced where from the **1.10** version. I have upgraded to **1.11** and the behavior that I have described above is still occurring. 

Thanks for the overview, that clears up my understanding of the PATCH request transaction flow.

To clarify my issue, when I submit a PATCH request, that includes attributes that my server application does not set into a resource (user/group), I can see the unwanted attributes in the response object.

# Example 1
**Request**

Given this request, I am updating a role. My server application ONLY uses the `roles.display` for server side validation. 
```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "add",
            "path": "roles",
            "value": [
                {
                    "primary": false,
                    "type": "WindowsAzureActiveDirectoryRole",
                    "display": "Role 2",
                    "value": "Something Irrelevant"
                },
            ]
        }
    ]
}
```

**Expected Response** 
* The expected output here is to only show the `roles.display`, since my server application sets the other attributes (value, type, primary) to null. 
* Noting that **Role 2** was added to the user (where Role 1 already existed).

```json
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    "id": "100325",
    "userName": "scim.test13",
    "displayName": "Dave",
    "active": true,
    "emails": [
        {
            "value": "dave@gmail.com",
            "type": "work",
            "primary": true
        }
    ],
    "phoneNumbers": [
        {
            "value": "551 1234",
            "type": "work"
        }
    ],
    "roles": [
        {
            "display": "Role 1"
        },
        {
            "display": "Role 2"
        }
    ],
    "meta": {
        "resourceType": "User",
        "created": "2021-04-23T02:15:38.378Z",
        "lastModified": "2021-07-21T17:45:13.223+10:00",
        "location": "https://********************/Users/100325",
        "version": "W/\"41BA1691F91FB9C9776DD2C18349540C051E59AD9E2339642B2CB0D32C7367D4FC7ABE6E9913B225A84B48E68AC2567BD2CF400149C6C9A93F5C84B1F5E98686\""
    }
}

```
* The bellow snippet is being called in my server application during the `ResourceHander.updateResource()`, as is used to create
  the returned object that should be returned to the API caller. 
* Due to the following snippet, I would expect the following output from this PATCH request (Noticing that roles only have `display` set.).

```java
List<PersonRole> userRoles = new ArrayList<PersonRole>();

if (roles != null && !roles.isEmpty())
{
	for (Role role : roles)
	{
		// Only the role.display is being set by my server application into the response object.
		userRoles.add(new PersonRole(null, null, role.getName(), null, null));
	}

	setRoles(userRoles);
}
```

**Actual Response** 
The current behavior shows that the new role (Role 2) that was added, is showing the other properties (value, type, primary), which I did not set into the role in my server application.

```json
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    "id": "100325",
    "userName": "scim.test13",
    "displayName": "Dave",
    "active": true,
    "emails": [
        {
            "value": "dave@gmail.com",
            "type": "work",
            "primary": true
        }
    ],
    "phoneNumbers": [
        {
            "value": "551 1234",
            "type": "work"
        }
    ],
    "roles": [
        {
            "display": "Role 1"
        },
        {
            "value": "Something Irrelevant",
            "display": "Role 2",
            "type": "WindowsAzureActiveDirectoryRole",
            "primary": false
        }
    ],
    "meta": {
        "resourceType": "User",
        "created": "2021-04-23T02:15:38.378Z",
        "lastModified": "2021-07-21T17:45:13.223+10:00",
        "location": "https://********************/Users/100325",
        "version": "W/\"41BA1691F91FB9C9776DD2C18349540C051E59AD9E2339642B2CB0D32C7367D4FC7ABE6E9913B225A84B48E68AC2567BD2CF400149C6C9A93F5C84B1F5E98686\""
    },
}
```

# Clarifications
* This behavior was not in 1.9.2, and became noticeable in 1.10. (and exists  in 1.11.0).
* I'd like to clarify that this behavior is not just for roles.
* From my testing, it to occur for any valid SCIM 2.0 attribute (defined in the user/group json).  

For example. 
> if my application did NOT set the x509Certificates property for a user, and an incoming PATCH request were to add or replace the attribute, the response object of the `ResourceHander.updateResource()` would show that value to be set  only in that response. 

# Example 2
**Request** 
A request to add x509Certificates (that my application does not use).

```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "add",
            "path": "x509Certificates",
            "value": [
                {
                    "type": "Something Irrelevant",
                    "value": "asdmjskaj1201i1290if12"
                }
            ]
        }
    ]
}
```

**Response**
The response contains 
```json
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    "id": "100325",
    "userName": "scim.test13",
    "displayName": "Dave",
    "active": true,
    "emails": [
        {
            "value": "dave@gmail.com",
            "type": "work",
            "primary": true
        }
    ],
    "phoneNumbers": [
        {
            "value": "551 1234",
            "type": "work"
        }
    ],
    "roles": [
        {
            "display": "Role 1"
        },
        {
            "display": "Role 2"
        }
    ],
    "x509Certificates": [
        {
            "value": "asdmjskaj1201i1290if12",
            "type": "Something Irrelevant"
        }
    ],
    "meta": {
        "resourceType": "User",
        "created": "2021-04-23T02:15:38.378Z",
        "lastModified": "2021-07-22T11:14:05.452+10:00",
        "location": "https://***********/Users/100325",
        "version": "W/\"A6F8990E09C496AE7779AF07CE6C16F141F8C09874B795E2D8172E1F64C1B6EF8BF8CC2ECFAC3C09A193B9578C63A862F76FCC6D48531A2708E58CEF8D35DB4F\""
    },
    "ermRequestId": "92f9fdfd-9681-41b7-89d9-0a8615326f7d"
}
```
In this case, I would expect that the `x509Certificates` would not appear in the response, since my application does not set it.

# Potential Suggestion

Could this be fixed by constructing the response object of `patchResource` with the resource coming from  `ResourceHandler.updateResource()`?

ResourceEndPointHandler:1054
```java
  // Constructing responseResource with patchedResourceNode instead of resourceNode so that the server application
 // has control over the resposne object.
  JsonNode responseResource = responseValidator.validateDocument(patchedResourceNode);
  return new UpdateResponse(responseResource, location, meta);
``` 

I hope this clears things up,

I would also like to mention, this is a fantastic library, brilliantly crafted, easy to use and well designed! 

Thanks in advance for your continued efforts here!

**Comment by Captain-P-Goldfish** [comment]
Okay now I got it. 
This was actually intentional behaviour because I was convinced that this is correct behaviour, so I tried to find the specific part in the specification but I noticed that either I am not able to find the corresponding part or this behaviour is indeed incorrect for attributes with a "returned" definition of "default"

RFC7643:
```
      returned  A single keyword that indicates when an attribute and
         associated values are returned in response to a GET request or
         in response to a PUT, POST, or PATCH request.  Valid keywords
         are as follows:

         always  The attribute is always returned, regardless of the
            contents of the "attributes" parameter.  For example, "id"
            is always returned to identify a SCIM resource.

         never  The attribute is never returned.  This may occur because
            the original attribute value (e.g., a hashed value) is not
            retained by the service provider.  A service provider MAY
            allow attributes to be used in a search filter.

         default  The attribute is returned by default in all SCIM
            operation responses where attribute values are returned.  If
            the GET request "attributes" parameter is specified,
            attribute values are only returned if the attribute is named
            in the "attributes" parameter.  DEFAULT.

         request  The attribute is returned in response to any PUT,
            POST, or PATCH operations if the attribute was specified by
            the client (for example, the attribute was modified).  The
            attribute is returned in a SCIM query operation only if
            specified in the "attributes" parameter.
```

The behaviour you are experiencing is actually for attributes of type "request" eventhough the attributes are having a "returned" value of "default".

## Whats happening

1. The SCIM-SDK creates a patched resource that is passed to the `updateResource` method. Now you are storing the resource and return a resource that is stripped of several values which is perfectly valid behaviour.
2. Now the schema-validation is executed
3. The schema-validation checks on the data of the patch-request which attributes were present within the patch-operations and treats these attributes as if they were present in the "attributes"-parameter and thus these attributes are extracted from the original patch-request and added into the response-resource

Thats basically what you are running into.

## Workaround

For the time being you'll be able to use a workaround. You can use the `excludedAttributes`-parameter in the patch-request as URL-query-parameter to exclude the attributes in question from the response.

**Comment by Captain-P-Goldfish** [comment]
Release is out. Should be available in the next few hours in maven central
