### ISSUE TITLE
Usage with Keycloak

### ISSUE THREAD

**Issue by wir33658** [Captain-P-Goldfish/SCIM-SDK#2]
Hi, as mentioned on https://issues.redhat.com/browse/KEYCLOAK-2537?_sscc=t
that this might be a good fit. Do you mind to share an example (e.g. on the Wiki) how to use it with Keycloak. That would be of great use. Thanks.

**Comment by Captain-P-Goldfish** [comment]
sure. I will provide an example in the next few days.

**Comment by Captain-P-Goldfish** [comment]
HI I provided an example and created a new release. I added a fix that makes the integration with wildfly 18 easier.

https://github.com/Captain-P-Goldfish/SCIM-SDK/tree/master/samples/scim-sdk-keycloak-example

refer to the README.MD that describes how the example can be deployed and tested.

**Comment by wir33658** [comment]
Thanks for the work. Thumbs up ;-).
