### ISSUE TITLE
master branch package de.captaingoldfish.scim.sdk.server.filter.antlr ScimFilter* java files is missing

### ISSUE THREAD

**Issue by Scout--** [Captain-P-Goldfish/SCIM-SDK#239]
master branch package de.captaingoldfish.scim.sdk.server.filter.antlr ScimFilter* java files is missing

**Comment by Captain-P-Goldfish** [comment]
These files are auto-generated by maven. Execute `mvn clean package` and you will find the files in `scim-sdk-server/target/generated-sources/antlr4`
