### ISSUE TITLE
No ResourceType object in scim-sdk-common

### ISSUE THREAD

**Issue by JackOfTheShadows** [Captain-P-Goldfish/SCIM-SDK#259]
Hi, I am implementing a client and would like to first check `/ResourceTypes` in order to discover the types of resources available on the SCIM service provider. I did not find any `ResourceType` object in `scim-sdk-common`, but found an implementation in the `scim-sdk-server`. Is there a reason why this object is not in `scim-sdk-common`? I can of course add the server as a dependency or just supply my own implementation of `ResourceType` but I am curious about why the object only exists in the server module.

**Comment by Captain-P-Goldfish** [comment]
I am aware of this problem. The problem here is that I added the SchemaFactory as internal member to the ResourceType object. This could probably be fixed by using an interface for which two implementations will be prepared. One for the server implementation and one for the client implementation.
