### ISSUE TITLE
Removing attributes from User schema

### ISSUE THREAD

**Issue by petersondrew** [Captain-P-Goldfish/SCIM-SDK#262]
Just had a quick question regarding the default User schema and the best practices section in the wiki.

If we want to remove attributes from the default User schema, is the proper way to create a new schema entirely? I tried modifying the schema by removing attributes at runtime (based on the [demonstration of modifying schema](https://github.com/Captain-P-Goldfish/SCIM-SDK/wiki/How-to-use-the-server-implementation#register-your-endpointdefinition) in the wiki) but it didn't appear to work.

Thanks!

**Comment by Captain-P-Goldfish** [comment]
Hi,
the way of overriding the user schema easier to understand in my eyes. If another developer looks into your code in two years it might be easier to understand that a custom schema is used if you copy and modify it. That is why I was suggesting doing so. Removing the attributes during runtime should also work though. Could you please explain the behaviour that you are experiencing?
It should be possible to remove attributes directly from the `de.captaingoldfish.scim.sdk.common.schemas.Schema` class and the change should take effect immediately.

**Comment by petersondrew** [comment]
Hmm, I was using `getMainSchema` of the `User` resource type I had registered, and when I would call `removeAttribute`, the attribute would still appear when calling the `/Schema` endpoint. 

I understand your suggestion on copying and modifying, I was concerned that maintainers might be confused by the `User` resource in the library compared to the custom `OtherUser` resource we'd be maintaining ourselves, so that's why I was experimenting with the runtime modifications.

**Comment by Captain-P-Goldfish** [comment]
I was just trying the following:

```java
    ResourceType userResourceType = resourceEndpoint.registerEndpoint(new UserEndpointDefinition(new UserHandler()));
    userResourceType.setFeatures(ResourceTypeFeatures.builder().autoFiltering(true).autoSorting(true).build());

    Schema mainSchema = userResourceType.getMainSchema();
    SchemaAttribute ims = mainSchema.getSchemaAttribute(AttributeNames.RFC7643.IMS);
```

and the /Schemas-Endpoint was no longer returning the `ims` -attribute. I you found a problem that causes the Schemas endpoint to return erroneous values please let me know but currently I cannot reproduce this problem.

I think this is also a perfectly fine and valid way of doing this if properly documented :-)

**Comment by petersondrew** [comment]
This was definitely my misunderstanding of the API. I was using `remove` and passing a property name that likely was not one of the constant values. Your example above cleared everything up, thanks so much!
