### ISSUE TITLE
Patching User:name sub-attributes via nested dot notation

### ISSUE THREAD

**Issue by JessThrysoee** [Captain-P-Goldfish/SCIM-SDK#267]
Azure AD send patches of the following form:

    {
      "schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
      "Operations": [
        {
          "op": "replace",
          "value": {
            "name.givenName": "captain",
            "name.familyName": "goldfish"
          }
        }
      ]
    }

The request is handled without error, but none of the values are replaced or visible in the response.

It looks like it gets updated as a simple attribute because getSchemaAttribute get called on the full key, instead of as a complex attribute:

https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/240b2c69d827398aa8efc3e1623a5e026e734a17/scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/patch/PatchResourceHandler.java#L111

Just as a test, it seems to update correctly with

    SchemaAttribute schemaAttribute = getSchemaAttribute((extensionUri == null ? "" : extensionUri + ":") + key.split("\\.")[0]); 

 

---
Microsoft documents this with an example request if their aadOptscim062020 feature flag is in use:

https://docs.microsoft.com/en-us/azure/active-directory/app-provisioning/application-provisioning-config-problem-scim-compatibility#flags-to-alter-the-scim-behavior

    {
      "schemas": [
          "urn:ietf:params:scim:api:messages:2.0:PatchOp"
      ],
      "Operations": [
          {
              "op": "replace",
              "path": "emails[type eq \"work\"].value",
              "value": "TestMhvaes@test.microsoft.com"
          },
          {
              "op": "replace",
              "value": {
                  "displayName": "Bjfe",
                  "name.givenName": "Kkom",
                  "name.familyName": "Unua",
                  "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:employeeNumber": "Aklq"
              }
          }
      ]
    }

**Comment by Captain-P-Goldfish** [comment]
Hi once again MS Azure is behaving incorrectly. The patch request is illegal and does not conform to RFC7644. This is similiar to https://github.com/Captain-P-Goldfish/SCIM-SDK/issues/193. I added a workaround handler there to fix a similiar erroneous request based on extensions.
