### ISSUE TITLE
Handling of multiple HTTP headers

### ISSUE THREAD

**Issue by sebastianloesch** [Captain-P-Goldfish/SCIM-SDK#28]
The class `ResourceEndpoint` defines methods to pass HTTP parameters as a map. As multiple HTTP header fields with the same field name appear in practice, the methods should use a multi map, e.g. javax.ws.rs.core.MultivaluedMap

**Comment by Captain-P-Goldfish** [comment]
please clarify why this is an issue for this api.
the api only checks if some specific headers are present within the request. I do not see a need for adding a MultiValuedMap here.
