### ISSUE TITLE
Feature a doAfterConsumer on ResourceEndpoint

### ISSUE THREAD

**Issue by sebastianloesch** [Captain-P-Goldfish/SCIM-SDK#29]
Currently it is possible to specify a doBeforeConsumer (e.g. for authentication handling).
It would be nice to be able to specify a doAfterConsumer also to handle the SCIMResponse, e.g. for different transaction behaviour depending on the response.

**Comment by Captain-P-Goldfish** [comment]
feature added. Will be available with the next release
