### ISSUE TITLE
Required Steps For Adding A New Schema ?

### ISSUE THREAD

**Issue by antoniolans** [Captain-P-Goldfish/SCIM-SDK#296]
Greetings,

Firstly, thank you for sharing this "SCIM 2.0" code implementation !

I have a few Schema questions which are as follows;

01) If I have a new ""urn:ietf:params:scim:schemas:extension:edicam:2.0:User" Schema, what are the necessary steps for adding it so that it will render in the "/scim/v2/Users" endpoint along with the "urn:ietf:params:scim:schemas:extension:edicam:2.0:User" Schema ?

02) What are the necessary steps for having the new ""urn:ietf:params:scim:schemas:extension:edicam:2.0:User" Schema displayed in the "/scim/v2/Schemas" endpoint along with the other Schemas?

03) In addition to "de.captaingoldfish.scim.sdk.common.constants.SchemaUris.java", which source code, packages, files, etc., would I be required to create/modify ?

Any suggestions would be greatly appreciated !  Thanks in advance for your kind assistance !

Respectfully,
A.L.

**Comment by Captain-P-Goldfish** [comment]
Hi, that is fairly simple to achieve by following these steps:

1. first write your new schema that you want to use as extension to the users-endpoint.
2. Create a new user-resource-type.json file:
```json
{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:ResourceType"
  ],
  "id": "User",
  "name": "User",
  "description": "User Account",
  "schema": "urn:ietf:params:scim:schemas:extension:edicam:2.0:User",
  "endpoint": "/Users",
  "meta": {
    "resourceType": "ResourceType",
    "created": "2019-10-18T14:51:11+02:00",
    "lastModified": "2019-10-18T14:51:11+02:00",
    "location": "/ResourceTypes/User"
  }
}
```
4. Create a POJO from your User-schema that extends the `ResourceNode` class just as the `de.captaingoldfish.scim.sdk.common.resources.User` does.
5. Create your `ResourceHandler` implementation. 
6. Create a new Endpoint Definition that reads your new schema and the resource-type file:
```java
public class EdicamUserEndpointDefinition extends EndpointDefinition
{

  public EdicamUserEndpointDefinition (ResourceHandler<EdicamUser> resourceHandler)
  {
    super(JsonHelper.loadJsonDocument(ClassPathReferences.EDICAM_USER_RESOURCE_TYPE_JSON),
          JsonHelper.loadJsonDocument(ClassPathReferences.EDICAM_USER_SCHEMA_JSON),
          null, resourceHandler);
  }
}
```
7. and finally register the `EndpointDefinition`: 
```java
ResourceType userResourceType = resourceEndpoint.registerEndpoint(new EdicamUserEndpointDefinition(userHandler));
```
that is all.

The register method will automatically add the new schema to the /Schemas and /ResourceType endpoints. No additional steps needed. The data is directly read from the json files.

It should not be necessary to modify any of the sourcecode or packages. You should be able to have fairly enough control of what the API will return.

**Comment by antoniolans** [comment]
Awesome and "MANY THANKS" for your kind assistance !
