### ISSUE TITLE
How Do I Pass A Payload ?

### ISSUE THREAD

**Issue by antoniolans** [Captain-P-Goldfish/SCIM-SDK#299]
Greetings,

When configuring a SCIM Client Java application, using the "ScimClientConfig" Object, how would I pass the following JSON payload in the request ?

{
   "schemas":[
         "urn:ietf:params:scim:schemas:extension:oracle:2.0:OIG:User"
   ],
   "urn:ietf:params:scim:schemas:extension:oracle:2.0:OIG:User":{
         "statusDescription":"Disabled by AIMS Emergency Disable,
         "statusReason":"Disabled by AIMS,
         "StatusTimestamp":"2022-07-06",
        "status":"Disabled"
   }
}

Please advise ?

Thanks in advance for your kind assistance !

Respectfully,
Antonio L.

**Comment by Captain-P-Goldfish** [comment]
This is currently possible in two ways:
1. Create a Java POJO representing this resource. You could do this easily by starting the `scim-sdk-schema-pojo-creator` and enter your resource schema into it to generate the pojo and adjust it to your needs. Afterwards you can put the java POJO as resource into the client
2. If you are using a string representation: this is currently not covered but you could do the following:
```
ScimHttpClient httpClient = new ScimHttpClient(scimClientConfig);
```
This object contains an underlying apache http client that is preconfigured with the configuration from the ScimClientConfig. Afterwards you can use the apache http client normally

**Comment by antoniolans** [comment]
Greetings "Captain-P-Goldfish",

You're the best !  

"MANY THANKS" !

Warmest Regards,
Antonio L.
