### ISSUE TITLE
Trying to create an user with an email allready used produces 500

### ISSUE THREAD

**Issue by csbrogi** [Captain-P-Goldfish/SCIM-SDK#3]
If you try to add an user with an email that is allready used by another user, a 500 - error with message:
{
    "error": "org.hibernate.exception.ConstraintViolationException: could not execute statement"
}
is returned.
It should return a meaningfull error.

**Comment by Captain-P-Goldfish** [comment]
the hibernate error cannot be handled by the scim-sdk. But I see that it might be useful to provide custom error messages with more details even in case of an internal server error. For this I added a new constructor to class `ErrorResponse` and extended the keycloak example in class `ScimEndpoint`.

The constructor will be available in the next release that comes in the next few days
