### ISSUE TITLE
Should declare public constructors on lombok builders

### ISSUE THREAD

**Issue by itineric** [Captain-P-Goldfish/SCIM-SDK#331]
You should specify public constructors on each lombok managed class so that projects extending these classes and also using lombok can provide Builders on their own classes.

See how its done here : https://stackoverflow.com/a/37752703

For instance: scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/endpoints/Context.java (ContextBuilder constructor has package visibility)

**Comment by Captain-P-Goldfish** [comment]
Will be done with 1.15.0.

**Comment by Captain-P-Goldfish** [comment]
I added the constructors but noticed also that there is an alternative way to get it done that does not need public constructors within the builders:

example 

``` java
@Test
  public void testExtendObject()
  {
    Assertions.assertDoesNotThrow(() -> ETagExtension.extensionBuilder().weak(true).tag("1").testValue("hello").build());
  }

public static class ETagExtension extends ETag
  {

    @Builder(builderMethodName = "extensionBuilder")
    public ETagExtension(Boolean weak, String tag, String testValue)
    {
      super(weak, tag);
    }
  }

```
