### ISSUE TITLE
Unexpected / misleading log on startup

### ISSUE THREAD

**Issue by itineric** [Captain-P-Goldfish/SCIM-SDK#335]
Hi,

I am doing some tests with your framework, I have the simpliest server implementation (it does nothing, just starts with a UserHandler and prints out what method is called). It works as expected.
On the first call to the /Users endpoint, the following log is displayed. I cannot find out why or what I am doing wrong.
Do you have a clue ?

```
INFO de.captaingoldfish.scim.sdk.server.schemas.ResourceTypeFactory - Resource schema with id 'urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig' is already registered. The new instance is not equal to the old schema document. The old document is being replaced by the new one
INFO de.captaingoldfish.scim.sdk.server.schemas.ResourceTypeFactory - Resource schema with id 'urn:ietf:params:scim:schemas:core:2.0:ResourceType' is already registered. The new instance is not equal to the old schema document. The old document is being replaced by the new one
INFO de.captaingoldfish.scim.sdk.server.schemas.ResourceTypeFactory - Resource schema with id 'urn:ietf:params:scim:schemas:core:2.0:Schema' is already registered. The new instance is not equal to the old schema document. The old document is being replaced by the new one
```

**Comment by Captain-P-Goldfish** [comment]
You are not doing anything wrong. It seems that on the first call the schemas seem to be reregistered. I will investigate. I actually fixed this once before... no idea why this is back...

**Comment by Captain-P-Goldfish** [comment]
I have no easy reliable fix for this. This seems to be a bug within jackson when comparing arrayNodes with complex objects within it with the equals method.
