### ISSUE TITLE
Context : getCrossResourceReferenceUrl always returns null

### ISSUE THREAD

**Issue by imihalcea** [Captain-P-Goldfish/SCIM-SDK#346]
I think there is a bug in getCrossResourceReferenceUrl method of the Context class defined as :

``` java 
public Optional<String> getCrossResourceReferenceUrl(String id, String resourceName)
  {
    return Optional.ofNullable(crossResourceReferenceUrl.apply(resourceName, id));
  }
```

but in ResourceEndpointHandler the crossResourceUrl bifunction is set to:

```java

  private Context getEffectiveContext(UriInfos uriInfos, Context context)
  {
    Context effectiveContext = Optional.ofNullable(context).orElse(new Context(null));
    effectiveContext.setResourceReferenceUrl(id -> {
      return super.getReferenceUrlSupplier(uriInfos::getBaseUri).apply(uriInfos.getResourceType().getName(), id);
    });
    effectiveContext.setCrossResourceReferenceUrl((resourceName, id) -> {
      return super.getReferenceUrlSupplier(uriInfos::getBaseUri).apply(id, resourceName); // <-- arguments inverted
    });
    return effectiveContext;
  }

BiFunction<String, String, String> getReferenceUrlSupplier(Supplier<String> baseUrl)
  {
    return (resourceName, resourceId) -> {
      Optional<ResourceType> resourceType = resourceTypeFactory.getResourceTypeByName(resourceName);
      String id = StringUtils.isBlank(resourceId) ? "" : "/" + resourceId;
      return resourceType.map(jsonNodes -> baseUrl.get() + jsonNodes.getEndpoint() + id).orElse(null);
    };
  }

```

We can see that the resourceId and resourceName parameters have been inverted and getCrossResourceReferenceUrl always returns null. 

The bug seems trivial to fix flipping the arguments in the getEffectiveContext will do the job, and the api is not changed. I think a test will be useful also. Would you accept a PR with the fix?

Of course I hope that the feature is not used because I haven't seen any issue on this topic, and I hope that no one did just flip the args when calling context.getCrossResourceReferenceUrl :)

**Comment by Captain-P-Goldfish** [comment]
this might be a breaking change for all those who simply switched the parameters. But this way its definitely better. Thx for pointing this out again.

**Comment by imihalcea** [comment]
thank's for the fix, do you know when it will be released ?
