### ISSUE TITLE
Allow SCIM_CONTENT_TYPE = "application/scim+json" validation override 

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [Captain-P-Goldfish/SCIM-SDK#399]
I am trying to implement this nice SDK, to connect to AWS SCIM service.
AWS is not SCIM compliant, and it has some [known limitations](https://docs.aws.amazon.com/singlesignon/latest/developerguide/limitations.html).
One blocking limitation from AWS, is that when calling SCIM service, it returns non scim compliant headers (application/json):
```
HTTP/2 201
date: Thu, 12 Jan 2023 00:49:57 GMT
content-type: application/json
content-length: 307
x-amzn-requestid: 2ee5483e-3544-45eb-8345-d631feddaefb
```
This SCIM-SDK [SeverResponse](https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/master/scim-sdk-client/src/main/java/de/captaingoldfish/scim/sdk/client/response/ServerResponse.java#L87) check for this headers to be application/scim+json .

Would it be possible to add a flag | option to override this .requiredResponseHeaders ? Or allow to define the SCIM_CONTENT_TYPE  value?

Thanks for this nice project!!

**Comment by Captain-P-Goldfish** [comment]
I will try to think of something nice.
For the time being I would recommend the following workaround:

```java
/**
   * extracts the request headers from the http request and puts them into a hash map
   *
   * @param httpExchange the server request and response object
   * @return the map with the request headers
   */
  private Map<String, String> getRequestHeaders(HttpExchange httpExchange)
  {
    Map<String, String> requestHeaders = new HashMap<>();
    for ( Map.Entry<String, List<String>> stringListEntry : httpExchange.getRequestHeaders().entrySet() )
    {
      requestHeaders.put(stringListEntry.getKey(), String.join(",", stringListEntry.getValue()));
    }
    final String contentType = requestHeaders.get(HttpHeader.CONTENT_TYPE_HEADER);
    if (contentType.equals(MediaType.APPLICATION_JSON))
    {
      requestHeaders.put(HttpHeader.CONTENT_TYPE_HEADER, HttpHeader.SCIM_CONTENT_TYPE);
    }
    return requestHeaders;
  }
```

**Comment by marcportabellaclotet-mt** [comment]
Thanks for the fast response.
I was thinking to add some optional logic [here](https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/master/scim-sdk-client/src/main/java/de/captaingoldfish/scim/sdk/client/builder/RequestBuilder.java#L198), but probably is not the best way to tackle it.
I did a workaround to temporally disable the getRequiredResponseHeaders validation, but it would be great to have this feature on your SDK.
My final goal is to build a keycloak SCIM client to be able to federate users with AWS. Based on this [project](https://lab.libreho.st/libre.sh/scim/keycloak-scim) . This project uses pingidentity/scim2-sdk which is not usable with AWS. (No optional fields are permitted in pingidentity)
Thanks again

**Comment by Captain-P-Goldfish** [comment]
Alright, you can handle this case now in two ways:

1. set the expected response-headers by default within the `ScimClientConfig`
```java
ScimClientConfig.builder().expectedHttpResponseHeaders(expectedHeaders).build()
```
this will override the headers by default. You have three options as documented:
```
/**
   * normally SCIM responses must have set the http-header "application/scim+json". But some providers are not
   * providing these headers. If so, set this map in order to modify the check of the response headers from the
   * server. <br>
   * <ul>
   * <li>null: The headers are checked as normally for the content-type "application/scim+json"</li>
   * <li>empty map: The check of response headers is disabled</li>
   * <li>filled map: The check of the response headers will be done with the entries of this map</li>
   * </ul>
   */
  private Map<String, String> expectedHttpResponseHeaders;
```
2. set the expected response-headers for a specific request when calling it:
```java 
response = scimRequestBuilder.create(getServerUrl() + EndpointPaths.USERS, User.class)
                                   .setExpectedResponseHeaders(expectedHeaders)
                                   .setResource(user)
                                   .sendRequest();
```

**Comment by marcportabellaclotet-mt** [comment]
I have already test it , and it works like a charm!
Thank you very much Pascal!
