### ISSUE TITLE
PatchBuilder operations generates quoted values in the value key, which may fail in some SCIM server

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [Captain-P-Goldfish/SCIM-SDK#404]
I am trying to create a patchbuild request like this:
```
List<Member> groupMembers = new ArrayList<>();
groupMembers.add(Member.builder()
    .value("333")
    .build());

 patchBuilder = scimRequestBuilder.patch("url", Group.class);
 patchBuilder.addOperation()
               .path("members")
               .op(PatchOp.REPLACE)
               .value(groupMembers.toString())
             .build();
LOGGER.info(patchBuilder.getResource());
```
The output from logger is:
```
{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"path":"members","op":"replace","value":"[{\"value\":\"333\"}]"}]}
```
In the above generated json payload, the value key content has been quoted and double quotes escaped ([{\"value\":\"333\"}]).
This payload does not work with AWS SCIM server, which by the way is really a bad scim implementation.
The same payload without quoting the value key, works as expected.

To workaround this, I create a jsonnode and object mapper, and then I use valueNode in the patch builder.

Is there any easier solution which allows to use value in the patchbuilder, and the payload don't get  quoted ?

Thanks again for this great SCIM-SDK!!

**Comment by Captain-P-Goldfish** [comment]
This is actually already possible. Do it like this:

```java
List<Member> groupMembers = new ArrayList<>();
groupMembers.add(Member.builder()
    .value("333")
    .build());

 patchBuilder = scimRequestBuilder.patch("url", Group.class);
 patchBuilder.addOperation()
               .path("members")
               .op(PatchOp.REPLACE)
               .valueNode(groupMembers)    <----- that is the important part
             .build();
LOGGER.info(patchBuilder.getResource());
```

**Comment by marcportabellaclotet-mt** [comment]
When I try with your suggestion, I get this error.
```
The method valueNode(JsonNode) in the type PatchBuilder.PatchOperationBuilder<Group> is not applicable for the arguments (List<Member>)
```
tested code : 
```
List<Member> groupMembers = new ArrayList<>();
groupMembers.add(Member.builder()
    .value("333")
    .build());
 
 PatchBuilder<Group> patchBuilder;
 patchBuilder = scimRequestBuilder.patch("url", Group.class);
 patchBuilder.addOperation()
               .path("members")
               .op(PatchOp.REPLACE)
               .valueNode(groupMembers)
             .build();
LOGGER.info(patchBuilder.getResource());
```
Thanks !!

**Comment by Captain-P-Goldfish** [comment]
ah sorry. The correct way here is currently of course to convert the list into an arrayNode

```java
ArrayNode arrayNode = new ArrayNode(JsonNodeFactory.instance);
arrayNode.add(Member.builder().value("333").build());
```

I think I could add a convenience method that will accept lists and will then convert the lists into array-nodes.

**Comment by marcportabellaclotet-mt** [comment]
That would be great!
Thanks for the tip.

**Comment by marcportabellaclotet-mt** [comment]
Tested with your last fix, and works like a charm.
Thanks again!!

**Comment by marcportabellaclotet-mt** [comment]
Do you know if a new public release of your sdk will be out soon? It would be great to integrate latest changes in the next release.
Thanks

**Comment by Captain-P-Goldfish** [comment]
sonatype is currently complaining about a vulnerability in jackson-databind. I will wait a few more days until this is fixed.

**Comment by marcportabellaclotet-mt** [comment]
Thanks

**Comment by Captain-P-Goldfish** [comment]
release is out

**Comment by marcportabellaclotet-mt** [comment]
Thanks again!!
