### ISSUE TITLE
Apparent Okta add members compatibility issue

### ISSUE THREAD

**Issue by davidmc24** [Captain-P-Goldfish/SCIM-SDK#419]
I have an Okta "SCIM 2.0 Test App (Header Auth)" test app set up to synchronize via SCIM to an application using scim-for-keycloak kc-18-b2.  It is set up with two "Push Groups" that appear to mostly synchronize users as expected.  When users are added to the groups, they are created in Keycloak.  When users are removed from the groups, they are disabled in Keycloak.  When attributes of the users are changed, the changes are reflected in Keycloak.  The part that isn't working is group memberships.  It appears that in Keycloak, the users never actually become members of the groups assigned in Okta, yet the Okta admin console doesn't show any errors.

Inspecting my application's logging, it appears that Okta is sending requests to `PATCH /identity/scim/v2/Groups/47381c23-a95a-4341-b653-8674c974805b` of this form:

```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "add",
      "path": "members",
      "value": [
        {
          "value": "2900df44-a197-4ca6-bad2-3c1b5641ac8e",
          "display": "ABaker@Gradle.Example"
        }
      ]
    }
  ]
}
```

In particular, the omission of "type" from the value appears to be a problem.  I'm currently using a workaround in my application that, when it detects this situation, re-writes the request to default to type "User" before passing the request to the SCIM library.  I'm interested in what you think about this, and whether any optional workaround in this library would be appropriate.

**Comment by davidmc24** [comment]
Thanks for the response. Sorry for posting to the wrong project.

**Comment by Captain-P-Goldfish** [comment]
> Thanks for the response. Sorry for posting to the wrong project.

No problem. Just wanted to point that out. Might have sounded a bit aggressive, but it wasn't :-)
