### ISSUE TITLE
Users endpoint

### ISSUE THREAD

**Issue by clarklamgevin** [Captain-P-Goldfish/SCIM-SDK#431]
Sorry if asking a question via "issues" is not the right way; could not find any other way. Is there any documentation on how to implement a handler for the standard SCIM Users endpoint? I believe the schema and resource types are already defined. The Keystore server example is great, but it appears to me that much of what is needed for Users and Groups is already in the base code. Thanks in advance for your response.

**Comment by Captain-P-Goldfish** [comment]
I don't think I'm quite getting what you actually want. Could you give me some more details?
Does this example maybe help: https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/master/samples/scim-sdk-springboot-example/src/main/java/de/captaingoldfish/scim/sdk/springboot/sample/handler/UserHandler.java?

Or you could take a look into the scim-for-keycloak project that has a more advanced implementation: https://github.com/Captain-P-Goldfish/scim-for-keycloak/blob/master/scim-for-keycloak-server/src/main/java/de/captaingoldfish/scim/sdk/keycloak/scim/handler/UserHandler.java

**Comment by clarklamgevin** [comment]
Thank you. Will take a look at links you posted and will let you know

**Comment by clarklamgevin** [comment]
Thank you. All good. The springboot sample is exactly what I needed.
