### ISSUE TITLE
Migrate to Jakarta

### ISSUE THREAD

**Issue by lbenedetto** [Captain-P-Goldfish/SCIM-SDK#438]
Due to legal reasons javax had to be renamed to jakarta for a lot of packages.

https://mvnrepository.com/artifact/javax.ws.rs/javax.ws.rs-api has moved to https://mvnrepository.com/artifact/jakarta.ws.rs/jakarta.ws.rs-api

https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api has moved to https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api

To remain compatible with other software, this library must move to the jakarta namespace

**Comment by Captain-P-Goldfish** [comment]
fixed now with: 39656e965ad96f9fef501c515ae4a8d233161f6c
