### ISSUE TITLE
Is there support for schema extensions to User and Group?

### ISSUE THREAD

**Issue by clarklamgevin** [Captain-P-Goldfish/SCIM-SDK#444]
Trying to determine if the SDK supports extensions to User and Group schema. One use case is to extend User with a "custom entitlement" that captures attributes like this: "type: deny or allow", "operation: read", "protected object: select * from employee". Without this, I'd have to squash all of this into the standard SCIM entitlement's value which will require parsing by the client (e.g. [allow].[read].[select * from employee]. If supported, is there an example or document that shows how?

Thanks in advance.

**Comment by Captain-P-Goldfish** [comment]
forgot: If you do not know the paths to the standard resources. They are all set in constants in `ClassPathReferences`. Alternatively there is a preconfigured class `UserEndpointDefinition` that you can use as blueprint.

**Comment by clarklamgevin** [comment]
Thank you very much for your response. As always, prompt and thorough. I have already successfully registered and used custom resource types (modeled after your Keystore) and it worked flawlessly. I will try User and Group extensions and will let this forum know how it goes. 

Thank you.
