### ISSUE TITLE
Snyk scan is showing "Inadequate Encryption Strength" for ‎scim-sdk-client

### ISSUE THREAD

**Issue by ekos2001** [Captain-P-Goldfish/SCIM-SDK#517]
Tried to run Snyk scan across this project, may be you would like to fix this 
![image](https://github.com/Captain-P-Goldfish/SCIM-SDK/assets/12628077/5e3a70a5-8cf0-45e4-a064-9ca3cd3a7beb)

**Comment by Captain-P-Goldfish** [comment]
Sure. I will make this also configurable.
