### ISSUE TITLE
version choose in jdk 1.8 and spring boot 2

### ISSUE THREAD

**Issue by rensuperk** [Captain-P-Goldfish/SCIM-SDK#531]
Hello, 
Our project is using JDK 8 and Spring Boot 2.1.15.RELEASE, and there is no plan to upgrade in the short term.
Which version of scim-sdk-server should I choose?
When I started the application, some errors were reported. 
Here are the detailed logs. 
Could you tell me where the errors are coming from?
Please give me some useful suggestions.
Thanks 

`C:\app\Zulu\zulu-8\bin\java.exe -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.3\lib\idea_rt.jar=63529:C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.3\bin" -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dfile.encoding=UTF-8 -classpath C:\app\Zulu\zulu-8\jre\lib\cat.jar;C:\app\Zulu\zulu-8\jre\lib\charsets.jar;C:\app\Zulu\zulu-8\jre\lib\ext\access-bridge-64.jar;C:\app\Zulu\zulu-8\jre\lib\ext\cldrdata.jar;C:\app\Zulu\zulu-8\jre\lib\ext\crs-agent.jar;C:\app\Zulu\zulu-8\jre\lib\ext\dnsns.jar;C:\app\Zulu\zulu-8\jre\lib\ext\jaccess.jar;C:\app\Zulu\zulu-8\jre\lib\ext\localedata.jar;C:\app\Zulu\zulu-8\jre\lib\ext\nashorn.jar;C:\app\Zulu\zulu-8\jre\lib\ext\sunec.jar;C:\app\Zulu\zulu-8\jre\lib\ext\sunjce_provider.jar;C:\app\Zulu\zulu-8\jre\lib\ext\sunmscapi.jar;C:\app\Zulu\zulu-8\jre\lib\ext\sunpkcs11.jar;C:\app\Zulu\zulu-8\jre\lib\ext\zipfs.jar;C:\app\Zulu\zulu-8\jre\lib\jce.jar;C:\app\Zulu\zulu-8\jre\lib\jfr.jar;C:\app\Zulu\zulu-8\jre\lib\jsse.jar;C:\app\Zulu\zulu-8\jre\lib\management-agent.jar;C:\app\Zulu\zulu-8\jre\lib\resources.jar;C:\app\Zulu\zulu-8\jre\lib\rt.jar;C:\Users\EDY\IdeaProjects\scim-sdk-springboot-test\target\classes;C:\Users\EDY\.m2\repository\org\springframework\boot\spring-boot-starter\2.1.15.RELEASE\spring-boot-starter-2.1.15.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\boot\spring-boot\2.1.15.RELEASE\spring-boot-2.1.15.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\spring-context\5.1.16.RELEASE\spring-context-5.1.16.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\boot\spring-boot-autoconfigure\2.1.15.RELEASE\spring-boot-autoconfigure-2.1.15.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\boot\spring-boot-starter-logging\2.1.15.RELEASE\spring-boot-starter-logging-2.1.15.RELEASE.jar;C:\Users\EDY\.m2\repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;C:\Users\EDY\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;C:\Users\EDY\.m2\repository\org\apache\logging\log4j\log4j-to-slf4j\2.11.2\log4j-to-slf4j-2.11.2.jar;C:\Users\EDY\.m2\repository\org\slf4j\jul-to-slf4j\1.7.30\jul-to-slf4j-1.7.30.jar;C:\Users\EDY\.m2\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;C:\Users\EDY\.m2\repository\org\springframework\spring-core\5.1.16.RELEASE\spring-core-5.1.16.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\spring-jcl\5.1.16.RELEASE\spring-jcl-5.1.16.RELEASE.jar;C:\Users\EDY\.m2\repository\org\yaml\snakeyaml\1.23\snakeyaml-1.23.jar;C:\Users\EDY\.m2\repository\org\springframework\boot\spring-boot-starter-web\2.1.15.RELEASE\spring-boot-starter-web-2.1.15.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\boot\spring-boot-starter-json\2.1.15.RELEASE\spring-boot-starter-json-2.1.15.RELEASE.jar;C:\Users\EDY\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.9.10\jackson-datatype-jdk8-2.9.10.jar;C:\Users\EDY\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.9.10\jackson-datatype-jsr310-2.9.10.jar;C:\Users\EDY\.m2\repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.9.10\jackson-module-parameter-names-2.9.10.jar;C:\Users\EDY\.m2\repository\org\springframework\boot\spring-boot-starter-tomcat\2.1.15.RELEASE\spring-boot-starter-tomcat-2.1.15.RELEASE.jar;C:\Users\EDY\.m2\repository\org\apache\tomcat\embed\tomcat-embed-core\9.0.36\tomcat-embed-core-9.0.36.jar;C:\Users\EDY\.m2\repository\org\apache\tomcat\embed\tomcat-embed-el\9.0.36\tomcat-embed-el-9.0.36.jar;C:\Users\EDY\.m2\repository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.36\tomcat-embed-websocket-9.0.36.jar;C:\Users\EDY\.m2\repository\org\hibernate\validator\hibernate-validator\6.0.20.Final\hibernate-validator-6.0.20.Final.jar;C:\Users\EDY\.m2\repository\javax\validation\validation-api\2.0.1.Final\validation-api-2.0.1.Final.jar;C:\Users\EDY\.m2\repository\org\jboss\logging\jboss-logging\3.3.3.Final\jboss-logging-3.3.3.Final.jar;C:\Users\EDY\.m2\repository\com\fasterxml\classmate\1.4.0\classmate-1.4.0.jar;C:\Users\EDY\.m2\repository\org\springframework\spring-web\5.1.16.RELEASE\spring-web-5.1.16.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\spring-beans\5.1.16.RELEASE\spring-beans-5.1.16.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\spring-webmvc\5.1.16.RELEASE\spring-webmvc-5.1.16.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\spring-aop\5.1.16.RELEASE\spring-aop-5.1.16.RELEASE.jar;C:\Users\EDY\.m2\repository\org\springframework\spring-expression\5.1.16.RELEASE\spring-expression-5.1.16.RELEASE.jar;C:\Users\EDY\.m2\repository\de\captaingoldfish\scim-sdk-server\1.18.0\scim-sdk-server-1.18.0.jar;C:\Users\EDY\.m2\repository\de\captaingoldfish\scim-sdk-common\1.18.0\scim-sdk-common-1.18.0.jar;C:\Users\EDY\.m2\repository\org\antlr\antlr4\4.13.1\antlr4-4.13.1.jar;C:\Users\EDY\.m2\repository\org\antlr\antlr4-runtime\4.13.1\antlr4-runtime-4.13.1.jar;C:\Users\EDY\.m2\repository\org\antlr\antlr-runtime\3.5.3\antlr-runtime-3.5.3.jar;C:\Users\EDY\.m2\repository\org\antlr\ST4\4.3.4\ST4-4.3.4.jar;C:\Users\EDY\.m2\repository\org\abego\treelayout\org.abego.treelayout.core\1.0.3\org.abego.treelayout.core-1.0.3.jar;C:\Users\EDY\.m2\repository\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;C:\Users\EDY\.m2\repository\commons-io\commons-io\2.14.0\commons-io-2.14.0.jar;C:\Users\EDY\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.9.10.4\jackson-databind-2.9.10.4.jar;C:\Users\EDY\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.9.10\jackson-annotations-2.9.10.jar;C:\Users\EDY\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.9.10\jackson-core-2.9.10.jar;C:\Users\EDY\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;C:\Users\EDY\.m2\repository\org\apache\logging\log4j\log4j-core\2.11.2\log4j-core-2.11.2.jar;C:\Users\EDY\.m2\repository\org\apache\logging\log4j\log4j-api\2.11.2\log4j-api-2.11.2.jar;C:\Users\EDY\.m2\repository\org\apache\logging\log4j\log4j-slf4j2-impl\2.20.0\log4j-slf4j2-impl-2.20.0.jar;C:\Users\EDY\.m2\repository\org\projectlombok\lombok\1.18.12\lombok-1.18.12.jar com.weelfly.scimsdkspringboottest.ScimSpringbootSample

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.1.15.RELEASE)

2023-10-15 19:54:33.310  INFO 20812 --- [           main] c.w.s.ScimSpringbootSample               : Starting ScimSpringbootSample on WINDOWS-O6L4MFR with PID 20812 (C:\Users\EDY\IdeaProjects\scim-sdk-springboot-test\target\classes started by EDY in C:\Users\EDY\IdeaProjects\scim-sdk-springboot-test)
2023-10-15 19:54:33.315  INFO 20812 --- [           main] c.w.s.ScimSpringbootSample               : No active profile set, falling back to default profiles: default
2023-10-15 19:54:34.647  INFO 20812 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-10-15 19:54:34.677  INFO 20812 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-10-15 19:54:34.677  INFO 20812 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.36]
2023-10-15 19:54:34.778  INFO 20812 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-10-15 19:54:34.779  INFO 20812 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1402 ms
2023-10-15 19:54:34.937  WARN 20812 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'scimController' defined in file [C:\Users\EDY\IdeaProjects\scim-sdk-springboot-test\target\classes\com\weelfly\scimsdkspringboottest\controller\ScimController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getResourceEndpoint' defined in class path resource [com/weelfly/scimsdkspringboottest/config/WebAppConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint]: Factory method 'getResourceEndpoint' threw exception; nested exception is java.lang.NoSuchMethodError: de.captaingoldfish.scim.sdk.common.resources.base.ScimArrayNode.isEmpty()Z
2023-10-15 19:54:34.940  INFO 20812 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-10-15 19:54:34.951  INFO 20812 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-10-15 19:54:34.958 ERROR 20812 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    de.captaingoldfish.scim.sdk.server.schemas.validation.SimpleMultivaluedAttributeValidator.parseNodeType(SimpleMultivaluedAttributeValidator.java:73)

The following method did not exist:

    de.captaingoldfish.scim.sdk.common.resources.base.ScimArrayNode.isEmpty()Z

The method's class, de.captaingoldfish.scim.sdk.common.resources.base.ScimArrayNode, is available from the following locations:

    jar:file:/C:/Users/EDY/.m2/repository/de/captaingoldfish/scim-sdk-common/1.18.0/scim-sdk-common-1.18.0.jar!/de/captaingoldfish/scim/sdk/common/resources/base/ScimArrayNode.class

It was loaded from the following location:

    file:/C:/Users/EDY/.m2/repository/de/captaingoldfish/scim-sdk-common/1.18.0/scim-sdk-common-1.18.0.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of de.captaingoldfish.scim.sdk.common.resources.base.ScimArrayNode

Process finished with exit code 1
`

**Comment by Captain-P-Goldfish** [comment]
Hi, that is neither a JDK nor a spring problem. You have a version conflict with the jackson-data lib. Try to upgrade the jackson version in your dependency-management:

```xml
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>${version.jackson}</version>
</dependency>
```

It is always a good idea to use the `maven-enforcer-plugin` with the `<dependencyConvergence/>` configuration to prevent such errors.

**Comment by rensuperk** [comment]
After I upgraded the version of Jackson, it seems to work now. Thank you very much.
```
     <properties>
            <java.version>1.8</java.version>
            <maven.compiler.source>1.8</maven.compiler.source>
            <maven.compiler.target>1.8</maven.compiler.target>
            <jackson.version.core>2.11.0</jackson.version.core>
            <scim-sdk.version>1.18.0</scim-sdk.version>
            <springboot.version>2.1.15.RELEASE</springboot.version>
       </properties>
      <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-databind</artifactId>
          <version>${jackson.version.core}</version>
      </dependency>
      <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-core</artifactId>
          <version>${jackson.version.core}</version>
      </dependency>
      <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-annotations</artifactId>
          <version>${jackson.version.core}</version>
      </dependency>

```
