### ISSUE TITLE
Validation on response objects

### ISSUE THREAD

**Issue by palmique** [Captain-P-Goldfish/SCIM-SDK#542]
Hi,

does SCIM standard require to validate response data with schema definition? I don't think so.  But response is validated nevertheless, which is somehow strange to me, due to schema changes would invalidate existing data.

RFC7643: "Validation is performed by the receiver in the context of a SCIM protocol request (see RFC7644)."

If target system already contains data which do not match schema definition, why should querying those data cause an error?

Is there a chance to disable schema validation on response data?

**Comment by Captain-P-Goldfish** [comment]
It is not defined by SCIM. But it is a development help that prevents the developer making mistakes when building responses.

**Comment by hegedusm** [comment]
It would be possible to define the validation in the handler, something similar to how the request validation is done on update and create using de.captaingoldfish.scim.sdk.server.endpoints.ResourceHandler#getRequestValidator. If the handler defines a response validator use it (maybe return a default validator to keep the current logic), but implementations would be able to overwrite it in the handler if needed

**Comment by Captain-P-Goldfish** [comment]
that is basically possible. and easily done too. But I am basically reading "if". Is this a required feature on your side at the moment?

**Comment by hegedusm** [comment]
> that is basically possible. and easily done too. But I am basically reading "if". Is this a required feature on your side at the moment?

 Sometimes data is missing from the response, and it causes validation errors. We could handle these missing data upstream, but the validation error prevents anything to be done at the moment.

**Comment by PC-Chiu** [comment]
May I disable the validation on response objects？

**Comment by Captain-P-Goldfish** [comment]
There is currently no option to disable it and I actually do not see a good reason to deactivate it. It prevents you from accidentally revealing passwords on responses etc. 
But I would accept a pull-request that allows to disable response-validation by a configuration-variable just as the configuration variable `threadPool` in the `ServiceProvider` class.
