### ISSUE TITLE
Implementation of attributes and excludedAttributes in SearchRequest are not according to the SCIM RFC

### ISSUE THREAD

**Issue by SlavikZ** [Captain-P-Goldfish/SCIM-SDK#690]
For now, the `attributes` and `excludedAttributes` in the `SearchRequest` are implemented as a single string containing a comma-separated list of values. But, according to the [RFC 7644](https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.3), they must be a multi-valued list of strings, e.g. array of strings. Here is the sample from the RFC:
```
{
     "schemas": ["urn:ietf:params:scim:api:messages:2.0:SearchRequest"],
     "attributes": ["displayName", "userName"],
     "filter":
       "displayName sw \"smith\"",
     "startIndex": 1,
     "count": 10
   }
```

Thank you so much for your attention and the great SDK.

**Comment by Captain-P-Goldfish** [comment]
Now the API supports both. Array and comma separated list
