### ISSUE TITLE
Patch requests with valid ETag returns 412

### ISSUE THREAD

**Issue by Afira-Zahari-i2** [Captain-P-Goldfish/SCIM-SDK#746]
In my `UserHandler` class, I have set a new `meta.version` in the `updateResource` to correspond with a change in the resource. However, the PATCH request (with a valid `If-Match` header) ends up returning 412 stating `"eTag status of resource has changed"`. When I call the PUT (with a valid `If-Match` header) instead, the request is successful and in the response, I can see the new `meta.version` that I have set.

It seems like the `ResourceEndpoint#handleRequest` is validating the ETag _after_ calling `updateResource` for PATCH requests but for PUT requests, the validation is done _before_ calling `updateResource`.

**Comment by Captain-P-Goldfish** [comment]
you are right. This is a regression that I accidentally added with the rebuild of the patch implementation. I will fix it
