### ISSUE TITLE
Removing all Group members with PATCH request returns 400

### ISSUE THREAD

**Issue by klaudiabrisakova** [Captain-P-Goldfish/SCIM-SDK#757]
Hey,

according to [RFC](https://datatracker.ietf.org/doc/html/rfc7644#section-3.5.2.3) replacing all group members with PATCH request should work and it is indeed working. Based on that I would assume that also removing all group members witch PATCH request should work, but for a request like 
```
{
    "schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
    "Operations": [{
        "op": "replace",
        "path": "members",
        "value": []
    }]
}
```
the response is 400 Bad Request with body
```
{"detail":"Required sub-attribute 'urn:ietf:params:scim:schemas:core:2.0:Group:members.value' is missing in patch object.","schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"status":400,"errors":{"fieldErrors":{"members.value":["Required sub-attribute 'urn:ietf:params:scim:schemas:core:2.0:Group:members.value' is missing in patch object."]}}}
```

When you have application in Okta's OIN this is actually a request that Okta does when "Push now" for an empty group is triggered.
![Screenshot 2024-11-02 at 10 45 55](https://github.com/user-attachments/assets/ed2f7bef-dc35-470c-8a78-c2ee0448e257)

I tried checking if this was not caused by changes in the recent releases but looks like this never worked. In 1.25.1 and older I'm just getting a different response body
```
{"detail":"No target found for path-filter 'urn:ietf:params:scim:schemas:core:2.0:Group:members'","schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"status":400,"scimType":"noTarget"}
```

Thank you

**Comment by Captain-P-Goldfish** [comment]
Hi, that is true the behaviour did change because the PATCH implementation was completely rebuild.
I do agree that the current error message is not very good but the correct approach to clear an attribute would be with a remove operation and not with a replace operation.
I am also not sure if it is a good idea to handle an empty replace-operation as remove-operation.

**Comment by klaudiabrisakova** [comment]
Hey, 

I agree that it would be more correct to use remove operation, it's actually one of the examples in RFC7644
```
Remove all members of a group:

   PATCH /Groups/acbf3ae7-8463-...-9b4da3f908ce
   Host: example.com
   Accept: application/scim+json
   Content-Type: application/scim+json
   Authorization: Bearer h480djs93hd8
   If-Match: W/"a330bc54f0671c9"

   { "schemas":
      ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
     "Operations":[{
       "op":"remove","path":"members"
     }]
   }
```
At the same time it's not technically wrong to use also replace with empty array. 🤔

I think that library should support it. The biggest argument for me is that Okta is using such request. If it's not fixed here, we'll have to hack around it ourselves. I expect that most of the implementations want to integrate with Okta and therefore will have the same problem.

**Comment by Captain-P-Goldfish** [comment]
The easiest way to support this would be do translate a replace-operation with an empty value with a delete-operation in the class `PatchRequestHandler`. Do you want to provide a pull-request?

**Comment by Captain-P-Goldfish** [comment]
no, this is actually the behaviour that would be intended for replace with a non-matching filter. In case of remove it should indicate success.

**Comment by klaudiabrisakova** [comment]
🤔 So it's a bug. I need to fix this first to be able to fix the original issue. I'll try to prepare a PR, if I need help I will reach out to you.

**Comment by klaudiabrisakova** [comment]
I was able to resolve the problem with `noTarget` by enabling `.doNotFailOnNoTarget(true)`. Now I'm a bit confused. 
Is what I described [here](https://github.com/Captain-P-Goldfish/SCIM-SDK/issues/757#issuecomment-2460627654) a bug or not?

**Comment by Captain-P-Goldfish** [comment]
sorry for the very late reply. Forgot to answer in the email flood...
Yes it is still a bug. The option you selected is just an option because some providers are expecting different results just as you experienced here.
